name: CuongOrigami
favicon: null
layout_spectrum: 0
typography_spectrum: 0.29872
title: Origami world of Nguyen Hung Cuong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe2e9'
    - '#171925'
    - '#927965'
    - '#004f91'
    - '#3081c2'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
