name: CuongOrigami
favicon: null
layout_spectrum: 0.75445
typography_spectrum: 0.38491
title: Origami world of Nguyen Hung Cuong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6ebf1'
    - '#999ba2'
    - '#6d6268'
    - '#191014'
    - '#3d3433'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
