typography_spectrum: 0.75312
color:
  brandColors:
    - '#e6ebf1'
    - '#999ba2'
    - '#6d6268'
    - '#191014'
    - '#3d3433'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30142
analytics:
  google: null
  facebook: null
  twitter: null
name: CuongOrigami
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Origami
description: Save the paper!
purpose: []
