name: CuongOrigami
favicon: null
layout_spectrum: 0.6259
typography_spectrum: 1
title: Origami world of Nguyen Hung Cuong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe2e9'
    - '#171925'
    - '#927965'
    - '#004f91'
    - '#3081c2'
  brandStrength: 0.8125
  lightness: 0.2791549824178219
  saturation: 0.5
  rhythmicContrast: 0.4815393730532378
purpose: []
