name: CuongOrigami
favicon: null
layout_spectrum: 0.13618
typography_spectrum: 0.41038
title: Origami world of Nguyen Hung Cuong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe2e9'
    - '#171925'
    - '#927965'
    - '#004f91'
    - '#3081c2'
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
